### ISSUE TITLE
Change status Message timeout 

### ISSUE THREAD

**Issue by 3ripleM** [Hameds/CodeChampion-vscode#8]
Now it's set on 2000ms but I think it's better to get the song duration and set the timeout to it.

**Comment by 3ripleM** [comment]
resolved in #11

**Comment by Hameds** [comment]
What happens to message timeout if a user hit `f12` to stop the current song?

**Comment by 3ripleM** [comment]
It will dispose when user hit `f12` its on line 93 at my PR

**Comment by Hameds** [comment]
@3ripleM thanks for the reply. I will check the code and merge it :)

**Comment by 3ripleM** [comment]
@Hameds I have resolved conflict at #11 🤔
